logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ./logs/monitoring.log
      archivedLogFilenamePattern: ./logs/monitoring.log.%d.gz
      archivedFileCount: 10

server:
  applicationConnectors:
    - type: http
      port: 8080

